# Generated by Django 6.0.6 on 2026-07-07 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('ipa', models.CharField(help_text='IPA-Transkription', max_length=200)),
                ('level', models.CharField(default='A1', max_length=10)),
                ('focus_segments', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='recordings/%Y/%m/%d/')),
                ('speaker', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('child', 'child')], default='male', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('done', 'done'), ('error', 'error')], default='pending', max_length=10)),
                ('result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TargetSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('speaker', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('child', 'child')], max_length=10)),
                ('f1_mean', models.FloatField()),
                ('f1_sd', models.FloatField()),
                ('f2_mean', models.FloatField()),
                ('f2_sd', models.FloatField()),
            ],
            options={
                'unique_together': {('phone', 'speaker')},
            },
        ),
    ]
