# Generated by Django 5.2.16 on 2026-07-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_learner_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='ist_referenz',
            field=models.BooleanField(default=False),
        ),
    ]
