# Generated by Django 5.2.16 on 2026-07-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_recording_ist_referenz'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='error_variants',
            field=models.JSONField(blank=True, default=list, help_text='Liste von Fehlaussprachen, z. B. [{"pron": "f l yː", "hinweis": "…"}]'),
        ),
        migrations.AddField(
            model_name='item',
            name='kind',
            field=models.CharField(choices=[('laut', 'laut'), ('wort', 'wort'), ('satz', 'satz')], default='wort', max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='mfa_pron',
            field=models.CharField(blank=True, default='', help_text='Soll-Lautung in MFA-Phonen, z. B. „f ʁ yː“', max_length=200),
        ),
    ]
