# Generated by Django 5.2.16 on 2026-07-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_seed_laut_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('dim', models.CharField(choices=[('f1', 'F1 (Mundöffnung)'), ('f2', 'F2 (Zunge horizontal)')], max_length=4)),
                ('direction', models.CharField(choices=[('high', 'zu hoch'), ('low', 'zu niedrig')], max_length=4)),
                ('text', models.TextField(help_text='Hinweis an die Lernenden — Schema „Mund …, Zunge …, Lippen …“, die Artikulatoren nicht vermischen.')),
            ],
            options={
                'unique_together': {('phone', 'dim', 'direction')},
            },
        ),
    ]
