# Generated by Django 5.2.16 on 2026-07-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_seed_feedback_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='beschreibung',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='gruppe',
            field=models.CharField(blank=True, choices=[('vorn_ungerundet', 'vordere, ungerundete Vokale'), ('vorn_gerundet', 'vordere, gerundete Vokale'), ('hinten_gerundet', 'hintere, gerundete Vokale')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='reference_audio',
            field=models.FileField(blank=True, null=True, upload_to='reference/'),
        ),
    ]
